dir_data: /home/mark/Development/Datasets/panama_papers/ #/data/panama_papers/
url_bearer: https://freepngimg.com/thumb/mask/2-2-anonymous-mask-png-hd-thumb.png
url_intermediary: https://static.thenounproject.com/png/195645-200.png
url_address: https://cdn1.iconfinder.com/data/icons/earth-environment/128/globes-14-512.png
url_company: https://img.pngio.com/party-building-company-company-building-home-icon-with-png-and-company-png-512_512.png
url_person: https://cdn.iconscout.com/icon/free/png-256/person-1767893-1502146.png
url_country_unknown: https://wiki.conworkshop.com/images/thumb/5/52/Unknown_Flag.png/300px-Unknown_Flag.png
